name: Website Uptime Check

# Disable the schedule trigger initially
on:
  # schedule:
  #   - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual trigger only

jobs:
  check_website:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Check website status
        run: python website_checker.py
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          
      - name: Commit and push log file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add uptime_log.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update uptime log [skip ci]" && git push)
